---
title: "final_proj"
author: "Maritza Ruiz and Steven Todd McIntyre II"
abstract: "placeholder"
format: 
  html:
    toc: true
bibliography: references.bib
execute:
  echo: false
  warning: false
---

# Introduction

# Methods

This analysis utilized R [@R] and the following R libraries: tidyverse [@tidyverse], rio [@rio], knitr [@knitr], here [@here], and janitor [@janitor].
```{r}
# load libraries
library(tidyverse)
library(rio)
library(here)
library(knitr)
library(janitor)

# must use:
# [x]   pivot_longer
# [x]    mutate
# []    select
# []    filter
# []    pivot_wider
# []    group_by
# []    summarize

# import and clean data
overall_persistence <- import(
    here("data/PersistenceandRetention2025_Appendix.xlsx"), 
    sheet = "1. Overall", 
    skip = 2
  ) |>
  pivot_longer(
    cols = c(
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
      "2022",
      "2023"
    ),
    names_to = "entering_cohort_year",
    values_to = "rate"
  ) |>
  clean_names() |>
  mutate(entering_cohort_year = as.numeric(entering_cohort_year))

  overall_persistence
```

# Results
```{r}
# create visualization A
overall_persistence |>
  filter(starting_enrollment_intensity == "All", metric == "Second Fall Persistence") |>
  ggplot(aes(x=entering_cohort_year, y=rate)) +
  geom_line(aes(color = sector)) 
  
  

```

# Discussion

# References
